COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True

  SQLALCHEMY_DATABASE_URI: 'mysql://root:1qw23e@localhost:3306/lab4'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql://root:1qw23e@localhost:3306/lab4'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: AXProduct2024
